# Generated by Django 6.0 on 2026-01-21 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('biography', models.TextField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('item_type', models.CharField(choices=[('book', 'Book'), ('ebook', 'E-Book'), ('journal', 'Journal'), ('magazine', 'Magazine')], default='book', max_length=20)),
                ('isbn', models.CharField(blank=True, db_index=True, max_length=20)),
                ('issn', models.CharField(blank=True, max_length=20)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('edition', models.CharField(blank=True, max_length=50)),
                ('classification_system', models.CharField(choices=[('dewey', 'Dewey Decimal'), ('loc', 'Library of Congress'), ('other', 'Other')], default='dewey', max_length=20)),
                ('classification_number', models.CharField(blank=True, max_length=50)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(default='English', max_length=50)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='item_covers/')),
                ('digital_file', models.FileField(blank=True, null=True, upload_to='digital_items/')),
                ('file_size_mb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(related_name='items', to='catalog.author')),
                ('categories', models.ManyToManyField(related_name='items', to='catalog.category')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.publisher')),
            ],
        ),
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=100, unique=True)),
                ('rfid_tag', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(help_text='Shelf location', max_length=200)),
                ('status', models.CharField(choices=[('available', 'Available'), ('checked_out', 'Checked Out'), ('reserved', 'Reserved'), ('damaged', 'Damaged'), ('lost', 'Lost'), ('in_repair', 'In Repair'), ('withdrawn', 'Withdrawn')], default='available', max_length=20)),
                ('condition', models.CharField(blank=True, max_length=100)),
                ('acquisition_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='branch.branch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='catalog.item')),
            ],
            options={
                'verbose_name_plural': 'Copies',
            },
        ),
    ]
